apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: eureka
          image: kaybee97/eureka
          ports:
            - containerPort: 8761
