apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: zuul
          image: kaybee97/zuul:v2
          ports:
            - containerPort: 8079
